# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - apiquentindocker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://apiquentindocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9892091073444c38a00febe50ea17871 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_77b5e5ea279d43f48b212cef9ffbfe17 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: apiquentindocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9892091073444c38a00febe50ea17871 }}/apiquentindocker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'apiquentindocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3f780dee857b47f49d37db344a176fc9 }}
        images: 'apiquentindocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9892091073444c38a00febe50ea17871 }}/apiquentindocker:${{ github.sha }}'